// Code generated by protoc-gen-go. DO NOT EDIT.
// source: entities.proto

package protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateUserRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Firstname            string   `protobuf:"bytes,3,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,4,opt,name=lastname,proto3" json:"lastname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f7344b79fcc63d, []int{0}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateUserRequest) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *CreateUserRequest) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

type CreateUserReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserReply) Reset()         { *m = CreateUserReply{} }
func (m *CreateUserReply) String() string { return proto.CompactTextString(m) }
func (*CreateUserReply) ProtoMessage()    {}
func (*CreateUserReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f7344b79fcc63d, []int{1}
}

func (m *CreateUserReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserReply.Unmarshal(m, b)
}
func (m *CreateUserReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserReply.Marshal(b, m, deterministic)
}
func (m *CreateUserReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserReply.Merge(m, src)
}
func (m *CreateUserReply) XXX_Size() int {
	return xxx_messageInfo_CreateUserReply.Size(m)
}
func (m *CreateUserReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserReply proto.InternalMessageInfo

type GetUserRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f7344b79fcc63d, []int{2}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetUserAuthenticateRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserAuthenticateRequest) Reset()         { *m = GetUserAuthenticateRequest{} }
func (m *GetUserAuthenticateRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserAuthenticateRequest) ProtoMessage()    {}
func (*GetUserAuthenticateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f7344b79fcc63d, []int{3}
}

func (m *GetUserAuthenticateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserAuthenticateRequest.Unmarshal(m, b)
}
func (m *GetUserAuthenticateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserAuthenticateRequest.Marshal(b, m, deterministic)
}
func (m *GetUserAuthenticateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserAuthenticateRequest.Merge(m, src)
}
func (m *GetUserAuthenticateRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserAuthenticateRequest.Size(m)
}
func (m *GetUserAuthenticateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserAuthenticateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserAuthenticateRequest proto.InternalMessageInfo

func (m *GetUserAuthenticateRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetUserAuthenticateRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserData struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Firstname            string   `protobuf:"bytes,3,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,4,opt,name=lastname,proto3" json:"lastname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserData) Reset()         { *m = UserData{} }
func (m *UserData) String() string { return proto.CompactTextString(m) }
func (*UserData) ProtoMessage()    {}
func (*UserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f7344b79fcc63d, []int{4}
}

func (m *UserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserData.Unmarshal(m, b)
}
func (m *UserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserData.Marshal(b, m, deterministic)
}
func (m *UserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserData.Merge(m, src)
}
func (m *UserData) XXX_Size() int {
	return xxx_messageInfo_UserData.Size(m)
}
func (m *UserData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserData.DiscardUnknown(m)
}

var xxx_messageInfo_UserData proto.InternalMessageInfo

func (m *UserData) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserData) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserData) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *UserData) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

type GetBookRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBookRequest) Reset()         { *m = GetBookRequest{} }
func (m *GetBookRequest) String() string { return proto.CompactTextString(m) }
func (*GetBookRequest) ProtoMessage()    {}
func (*GetBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f7344b79fcc63d, []int{5}
}

func (m *GetBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookRequest.Unmarshal(m, b)
}
func (m *GetBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookRequest.Marshal(b, m, deterministic)
}
func (m *GetBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookRequest.Merge(m, src)
}
func (m *GetBookRequest) XXX_Size() int {
	return xxx_messageInfo_GetBookRequest.Size(m)
}
func (m *GetBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookRequest proto.InternalMessageInfo

func (m *GetBookRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetBookRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetBookReply struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Body                 string   `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Genre                int32    `protobuf:"varint,5,opt,name=genre,proto3" json:"genre,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBookReply) Reset()         { *m = GetBookReply{} }
func (m *GetBookReply) String() string { return proto.CompactTextString(m) }
func (*GetBookReply) ProtoMessage()    {}
func (*GetBookReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f7344b79fcc63d, []int{6}
}

func (m *GetBookReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookReply.Unmarshal(m, b)
}
func (m *GetBookReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookReply.Marshal(b, m, deterministic)
}
func (m *GetBookReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookReply.Merge(m, src)
}
func (m *GetBookReply) XXX_Size() int {
	return xxx_messageInfo_GetBookReply.Size(m)
}
func (m *GetBookReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookReply proto.InternalMessageInfo

func (m *GetBookReply) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetBookReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetBookReply) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *GetBookReply) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *GetBookReply) GetGenre() int32 {
	if m != nil {
		return m.Genre
	}
	return 0
}

type ListBooksRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBooksRequest) Reset()         { *m = ListBooksRequest{} }
func (m *ListBooksRequest) String() string { return proto.CompactTextString(m) }
func (*ListBooksRequest) ProtoMessage()    {}
func (*ListBooksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f7344b79fcc63d, []int{7}
}

func (m *ListBooksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBooksRequest.Unmarshal(m, b)
}
func (m *ListBooksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBooksRequest.Marshal(b, m, deterministic)
}
func (m *ListBooksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBooksRequest.Merge(m, src)
}
func (m *ListBooksRequest) XXX_Size() int {
	return xxx_messageInfo_ListBooksRequest.Size(m)
}
func (m *ListBooksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBooksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListBooksRequest proto.InternalMessageInfo

func (m *ListBooksRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type ListBooksReply struct {
	Books                []*ListBook `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListBooksReply) Reset()         { *m = ListBooksReply{} }
func (m *ListBooksReply) String() string { return proto.CompactTextString(m) }
func (*ListBooksReply) ProtoMessage()    {}
func (*ListBooksReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f7344b79fcc63d, []int{8}
}

func (m *ListBooksReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBooksReply.Unmarshal(m, b)
}
func (m *ListBooksReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBooksReply.Marshal(b, m, deterministic)
}
func (m *ListBooksReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBooksReply.Merge(m, src)
}
func (m *ListBooksReply) XXX_Size() int {
	return xxx_messageInfo_ListBooksReply.Size(m)
}
func (m *ListBooksReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBooksReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListBooksReply proto.InternalMessageInfo

func (m *ListBooksReply) GetBooks() []*ListBook {
	if m != nil {
		return m.Books
	}
	return nil
}

type ListBook struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Genre                int32    `protobuf:"varint,4,opt,name=genre,proto3" json:"genre,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBook) Reset()         { *m = ListBook{} }
func (m *ListBook) String() string { return proto.CompactTextString(m) }
func (*ListBook) ProtoMessage()    {}
func (*ListBook) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f7344b79fcc63d, []int{9}
}

func (m *ListBook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBook.Unmarshal(m, b)
}
func (m *ListBook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBook.Marshal(b, m, deterministic)
}
func (m *ListBook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBook.Merge(m, src)
}
func (m *ListBook) XXX_Size() int {
	return xxx_messageInfo_ListBook.Size(m)
}
func (m *ListBook) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBook.DiscardUnknown(m)
}

var xxx_messageInfo_ListBook proto.InternalMessageInfo

func (m *ListBook) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ListBook) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListBook) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ListBook) GetGenre() int32 {
	if m != nil {
		return m.Genre
	}
	return 0
}

type CreateBookRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBookRequest) Reset()         { *m = CreateBookRequest{} }
func (m *CreateBookRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBookRequest) ProtoMessage()    {}
func (*CreateBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f7344b79fcc63d, []int{10}
}

func (m *CreateBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBookRequest.Unmarshal(m, b)
}
func (m *CreateBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBookRequest.Marshal(b, m, deterministic)
}
func (m *CreateBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBookRequest.Merge(m, src)
}
func (m *CreateBookRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBookRequest.Size(m)
}
func (m *CreateBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBookRequest proto.InternalMessageInfo

func (m *CreateBookRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type CreateBookReply struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBookReply) Reset()         { *m = CreateBookReply{} }
func (m *CreateBookReply) String() string { return proto.CompactTextString(m) }
func (*CreateBookReply) ProtoMessage()    {}
func (*CreateBookReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f7344b79fcc63d, []int{11}
}

func (m *CreateBookReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBookReply.Unmarshal(m, b)
}
func (m *CreateBookReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBookReply.Marshal(b, m, deterministic)
}
func (m *CreateBookReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBookReply.Merge(m, src)
}
func (m *CreateBookReply) XXX_Size() int {
	return xxx_messageInfo_CreateBookReply.Size(m)
}
func (m *CreateBookReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBookReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBookReply proto.InternalMessageInfo

func (m *CreateBookReply) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UpdateBookRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Body                 string   `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	Genre                int32    `protobuf:"varint,6,opt,name=genre,proto3" json:"genre,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBookRequest) Reset()         { *m = UpdateBookRequest{} }
func (m *UpdateBookRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateBookRequest) ProtoMessage()    {}
func (*UpdateBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f7344b79fcc63d, []int{12}
}

func (m *UpdateBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBookRequest.Unmarshal(m, b)
}
func (m *UpdateBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBookRequest.Marshal(b, m, deterministic)
}
func (m *UpdateBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBookRequest.Merge(m, src)
}
func (m *UpdateBookRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateBookRequest.Size(m)
}
func (m *UpdateBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBookRequest proto.InternalMessageInfo

func (m *UpdateBookRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UpdateBookRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateBookRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateBookRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UpdateBookRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *UpdateBookRequest) GetGenre() int32 {
	if m != nil {
		return m.Genre
	}
	return 0
}

type UpdateBookReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBookReply) Reset()         { *m = UpdateBookReply{} }
func (m *UpdateBookReply) String() string { return proto.CompactTextString(m) }
func (*UpdateBookReply) ProtoMessage()    {}
func (*UpdateBookReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f7344b79fcc63d, []int{13}
}

func (m *UpdateBookReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBookReply.Unmarshal(m, b)
}
func (m *UpdateBookReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBookReply.Marshal(b, m, deterministic)
}
func (m *UpdateBookReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBookReply.Merge(m, src)
}
func (m *UpdateBookReply) XXX_Size() int {
	return xxx_messageInfo_UpdateBookReply.Size(m)
}
func (m *UpdateBookReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBookReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBookReply proto.InternalMessageInfo

type DeleteBookRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBookRequest) Reset()         { *m = DeleteBookRequest{} }
func (m *DeleteBookRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteBookRequest) ProtoMessage()    {}
func (*DeleteBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f7344b79fcc63d, []int{14}
}

func (m *DeleteBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBookRequest.Unmarshal(m, b)
}
func (m *DeleteBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBookRequest.Marshal(b, m, deterministic)
}
func (m *DeleteBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBookRequest.Merge(m, src)
}
func (m *DeleteBookRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteBookRequest.Size(m)
}
func (m *DeleteBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBookRequest proto.InternalMessageInfo

func (m *DeleteBookRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *DeleteBookRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteBookReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBookReply) Reset()         { *m = DeleteBookReply{} }
func (m *DeleteBookReply) String() string { return proto.CompactTextString(m) }
func (*DeleteBookReply) ProtoMessage()    {}
func (*DeleteBookReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f7344b79fcc63d, []int{15}
}

func (m *DeleteBookReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBookReply.Unmarshal(m, b)
}
func (m *DeleteBookReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBookReply.Marshal(b, m, deterministic)
}
func (m *DeleteBookReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBookReply.Merge(m, src)
}
func (m *DeleteBookReply) XXX_Size() int {
	return xxx_messageInfo_DeleteBookReply.Size(m)
}
func (m *DeleteBookReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBookReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBookReply proto.InternalMessageInfo

type GetSimpleGenerationRequest struct {
	SeedText             string   `protobuf:"bytes,1,opt,name=seed_text,json=seedText,proto3" json:"seed_text,omitempty"`
	Genre                int32    `protobuf:"varint,2,opt,name=genre,proto3" json:"genre,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSimpleGenerationRequest) Reset()         { *m = GetSimpleGenerationRequest{} }
func (m *GetSimpleGenerationRequest) String() string { return proto.CompactTextString(m) }
func (*GetSimpleGenerationRequest) ProtoMessage()    {}
func (*GetSimpleGenerationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f7344b79fcc63d, []int{16}
}

func (m *GetSimpleGenerationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSimpleGenerationRequest.Unmarshal(m, b)
}
func (m *GetSimpleGenerationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSimpleGenerationRequest.Marshal(b, m, deterministic)
}
func (m *GetSimpleGenerationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSimpleGenerationRequest.Merge(m, src)
}
func (m *GetSimpleGenerationRequest) XXX_Size() int {
	return xxx_messageInfo_GetSimpleGenerationRequest.Size(m)
}
func (m *GetSimpleGenerationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSimpleGenerationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSimpleGenerationRequest proto.InternalMessageInfo

func (m *GetSimpleGenerationRequest) GetSeedText() string {
	if m != nil {
		return m.SeedText
	}
	return ""
}

func (m *GetSimpleGenerationRequest) GetGenre() int32 {
	if m != nil {
		return m.Genre
	}
	return 0
}

type GetSimpleGenerationReply struct {
	Messages             []string `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSimpleGenerationReply) Reset()         { *m = GetSimpleGenerationReply{} }
func (m *GetSimpleGenerationReply) String() string { return proto.CompactTextString(m) }
func (*GetSimpleGenerationReply) ProtoMessage()    {}
func (*GetSimpleGenerationReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f7344b79fcc63d, []int{17}
}

func (m *GetSimpleGenerationReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSimpleGenerationReply.Unmarshal(m, b)
}
func (m *GetSimpleGenerationReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSimpleGenerationReply.Marshal(b, m, deterministic)
}
func (m *GetSimpleGenerationReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSimpleGenerationReply.Merge(m, src)
}
func (m *GetSimpleGenerationReply) XXX_Size() int {
	return xxx_messageInfo_GetSimpleGenerationReply.Size(m)
}
func (m *GetSimpleGenerationReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSimpleGenerationReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetSimpleGenerationReply proto.InternalMessageInfo

func (m *GetSimpleGenerationReply) GetMessages() []string {
	if m != nil {
		return m.Messages
	}
	return nil
}

type GetLargeGenerationRequest struct {
	SeedText             string   `protobuf:"bytes,1,opt,name=seed_text,json=seedText,proto3" json:"seed_text,omitempty"`
	Genre                int32    `protobuf:"varint,2,opt,name=genre,proto3" json:"genre,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLargeGenerationRequest) Reset()         { *m = GetLargeGenerationRequest{} }
func (m *GetLargeGenerationRequest) String() string { return proto.CompactTextString(m) }
func (*GetLargeGenerationRequest) ProtoMessage()    {}
func (*GetLargeGenerationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f7344b79fcc63d, []int{18}
}

func (m *GetLargeGenerationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLargeGenerationRequest.Unmarshal(m, b)
}
func (m *GetLargeGenerationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLargeGenerationRequest.Marshal(b, m, deterministic)
}
func (m *GetLargeGenerationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLargeGenerationRequest.Merge(m, src)
}
func (m *GetLargeGenerationRequest) XXX_Size() int {
	return xxx_messageInfo_GetLargeGenerationRequest.Size(m)
}
func (m *GetLargeGenerationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLargeGenerationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLargeGenerationRequest proto.InternalMessageInfo

func (m *GetLargeGenerationRequest) GetSeedText() string {
	if m != nil {
		return m.SeedText
	}
	return ""
}

func (m *GetLargeGenerationRequest) GetGenre() int32 {
	if m != nil {
		return m.Genre
	}
	return 0
}

type GetLargeGenerationReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLargeGenerationReply) Reset()         { *m = GetLargeGenerationReply{} }
func (m *GetLargeGenerationReply) String() string { return proto.CompactTextString(m) }
func (*GetLargeGenerationReply) ProtoMessage()    {}
func (*GetLargeGenerationReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5f7344b79fcc63d, []int{19}
}

func (m *GetLargeGenerationReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLargeGenerationReply.Unmarshal(m, b)
}
func (m *GetLargeGenerationReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLargeGenerationReply.Marshal(b, m, deterministic)
}
func (m *GetLargeGenerationReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLargeGenerationReply.Merge(m, src)
}
func (m *GetLargeGenerationReply) XXX_Size() int {
	return xxx_messageInfo_GetLargeGenerationReply.Size(m)
}
func (m *GetLargeGenerationReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLargeGenerationReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetLargeGenerationReply proto.InternalMessageInfo

func (m *GetLargeGenerationReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateUserRequest)(nil), "protos.CreateUserRequest")
	proto.RegisterType((*CreateUserReply)(nil), "protos.CreateUserReply")
	proto.RegisterType((*GetUserRequest)(nil), "protos.GetUserRequest")
	proto.RegisterType((*GetUserAuthenticateRequest)(nil), "protos.GetUserAuthenticateRequest")
	proto.RegisterType((*UserData)(nil), "protos.UserData")
	proto.RegisterType((*GetBookRequest)(nil), "protos.GetBookRequest")
	proto.RegisterType((*GetBookReply)(nil), "protos.GetBookReply")
	proto.RegisterType((*ListBooksRequest)(nil), "protos.ListBooksRequest")
	proto.RegisterType((*ListBooksReply)(nil), "protos.ListBooksReply")
	proto.RegisterType((*ListBook)(nil), "protos.ListBook")
	proto.RegisterType((*CreateBookRequest)(nil), "protos.CreateBookRequest")
	proto.RegisterType((*CreateBookReply)(nil), "protos.CreateBookReply")
	proto.RegisterType((*UpdateBookRequest)(nil), "protos.UpdateBookRequest")
	proto.RegisterType((*UpdateBookReply)(nil), "protos.UpdateBookReply")
	proto.RegisterType((*DeleteBookRequest)(nil), "protos.DeleteBookRequest")
	proto.RegisterType((*DeleteBookReply)(nil), "protos.DeleteBookReply")
	proto.RegisterType((*GetSimpleGenerationRequest)(nil), "protos.GetSimpleGenerationRequest")
	proto.RegisterType((*GetSimpleGenerationReply)(nil), "protos.GetSimpleGenerationReply")
	proto.RegisterType((*GetLargeGenerationRequest)(nil), "protos.GetLargeGenerationRequest")
	proto.RegisterType((*GetLargeGenerationReply)(nil), "protos.GetLargeGenerationReply")
}

func init() { proto.RegisterFile("entities.proto", fileDescriptor_a5f7344b79fcc63d) }

var fileDescriptor_a5f7344b79fcc63d = []byte{
	// 668 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x96, 0x6d, 0x6b, 0x13, 0x41,
	0x10, 0xc7, 0xb9, 0x4b, 0xd2, 0x24, 0x53, 0x49, 0x9b, 0xb5, 0x34, 0xd7, 0x53, 0xf0, 0x7a, 0x2f,
	0xa4, 0xa0, 0xf4, 0x45, 0x02, 0x3e, 0x80, 0x82, 0xd5, 0x42, 0x28, 0x96, 0x2a, 0xa7, 0x05, 0xc1,
	0x17, 0xe5, 0xd2, 0x9b, 0xc6, 0xd5, 0x4b, 0xee, 0xbc, 0xdd, 0x60, 0xf3, 0x46, 0x3f, 0x80, 0x5f,
	0xc1, 0x6f, 0xe2, 0x97, 0x93, 0xdd, 0x7b, 0xda, 0xdc, 0x43, 0x91, 0xd0, 0x57, 0xb9, 0xd9, 0xd9,
	0xf9, 0xef, 0x6f, 0x76, 0x67, 0x86, 0x40, 0x0f, 0xe7, 0x9c, 0x72, 0x8a, 0xec, 0x30, 0x8c, 0x02,
	0x1e, 0x90, 0x0d, 0xf9, 0xc3, 0xec, 0x5f, 0xd0, 0x7f, 0x13, 0xa1, 0xcb, 0xf1, 0x9c, 0x61, 0xe4,
	0xe0, 0xf7, 0x05, 0x32, 0x4e, 0x76, 0xa0, 0x85, 0x33, 0x97, 0xfa, 0x86, 0x66, 0x69, 0x07, 0x5d,
	0x27, 0x36, 0x88, 0x09, 0x9d, 0xd0, 0x65, 0xec, 0x47, 0x10, 0x79, 0x86, 0x2e, 0x1d, 0x99, 0x4d,
	0xee, 0x43, 0xf7, 0x8a, 0x46, 0x8c, 0xcf, 0xdd, 0x19, 0x1a, 0x0d, 0xe9, 0xcc, 0x17, 0x44, 0xa4,
	0xef, 0x26, 0xce, 0x66, 0x1c, 0x99, 0xda, 0x76, 0x1f, 0xb6, 0x54, 0x80, 0xd0, 0x5f, 0xda, 0x16,
	0xf4, 0xc6, 0xc8, 0x55, 0xa0, 0x1e, 0xe8, 0xd4, 0x93, 0x34, 0x0d, 0x47, 0xa7, 0x9e, 0x7d, 0x06,
	0x66, 0xb2, 0xe3, 0x68, 0xc1, 0xbf, 0x88, 0xd4, 0x2e, 0x5d, 0x8e, 0x6b, 0xe3, 0xdb, 0x5f, 0xa1,
	0x23, 0xc4, 0x8e, 0x5d, 0xee, 0x16, 0xcf, 0xca, 0xd5, 0x74, 0x55, 0x6d, 0xfd, 0x84, 0x9f, 0xcb,
	0xec, 0x5e, 0x07, 0xc1, 0xb7, 0x9a, 0xec, 0xc8, 0x00, 0xda, 0x0b, 0x86, 0xd1, 0x05, 0x8d, 0x41,
	0x1b, 0xce, 0x86, 0x30, 0x4f, 0x3c, 0xfb, 0x27, 0xdc, 0xc9, 0x42, 0x43, 0x7f, 0x59, 0x0a, 0x24,
	0xd0, 0x94, 0x47, 0xc6, 0xa4, 0xf2, 0x9b, 0x58, 0xb0, 0xe9, 0x21, 0xbb, 0x8c, 0x68, 0xc8, 0x69,
	0x30, 0x4f, 0x50, 0xd5, 0x25, 0x11, 0x35, 0x09, 0xbc, 0x65, 0x02, 0x2a, 0xbf, 0x45, 0xd2, 0x53,
	0x9c, 0x47, 0x68, 0xb4, 0x2c, 0xed, 0xa0, 0xe5, 0xc4, 0x86, 0xfd, 0x08, 0xb6, 0x4f, 0x29, 0x93,
	0x00, 0x2c, 0x85, 0x57, 0x60, 0xb5, 0x15, 0xd8, 0x67, 0xd0, 0x53, 0x36, 0x0b, 0xdc, 0x87, 0xd0,
	0x9a, 0x08, 0xcb, 0xd0, 0xac, 0xc6, 0xc1, 0xe6, 0x70, 0x3b, 0x2e, 0x45, 0x76, 0x98, 0x6e, 0x73,
	0x62, 0xb7, 0x7d, 0x05, 0x9d, 0x74, 0xe9, 0x96, 0x52, 0xcc, 0xd2, 0x69, 0xaa, 0xe9, 0x3c, 0x4e,
	0x6b, 0x5f, 0x7d, 0x8c, 0xda, 0x7c, 0xf6, 0xd3, 0x42, 0xad, 0xbd, 0x7f, 0xfb, 0x8f, 0x06, 0xfd,
	0xf3, 0xd0, 0xfb, 0x4f, 0xc5, 0x24, 0x5c, 0x2f, 0xe5, 0xd6, 0xa8, 0xcf, 0xad, 0x59, 0xff, 0x7c,
	0xad, 0xaa, 0xe7, 0xdb, 0x50, 0xf3, 0xed, 0xc3, 0x96, 0x4a, 0x27, 0x5a, 0xed, 0x05, 0xf4, 0x8f,
	0xd1, 0xc7, 0xf5, 0x80, 0x85, 0xa0, 0x1a, 0x2d, 0x04, 0xdf, 0xc9, 0xce, 0xfc, 0x40, 0x67, 0xa1,
	0x8f, 0x63, 0x9c, 0x63, 0xe4, 0x0a, 0xc8, 0x54, 0xf9, 0x1e, 0x74, 0x19, 0xa2, 0x77, 0xc1, 0xf1,
	0x9a, 0x27, 0xdd, 0xd9, 0x11, 0x0b, 0x1f, 0xf1, 0x9a, 0xe7, 0xd0, 0xba, 0x0a, 0xfd, 0x04, 0x8c,
	0x4a, 0x41, 0x71, 0xff, 0x26, 0x74, 0x66, 0xc8, 0x98, 0x3b, 0xc5, 0xb8, 0xa6, 0xba, 0x4e, 0x66,
	0xdb, 0x67, 0xb0, 0x37, 0x46, 0x7e, 0xea, 0x46, 0xd3, 0xdb, 0xe1, 0x18, 0xc1, 0xa0, 0x4a, 0x4f,
	0x60, 0x18, 0xd0, 0x4e, 0x8e, 0x4d, 0xb4, 0x52, 0x73, 0xf8, 0xbb, 0x09, 0xed, 0xf7, 0x18, 0x31,
	0xca, 0x38, 0x79, 0x05, 0x90, 0x0f, 0x3a, 0xb2, 0x97, 0x16, 0x7f, 0x69, 0xfa, 0x9a, 0x83, 0x2a,
	0x97, 0x38, 0x67, 0x04, 0xed, 0x64, 0xea, 0x91, 0xdd, 0x74, 0xcf, 0xea, 0xa0, 0x34, 0xb3, 0x9e,
	0xca, 0xc6, 0xd9, 0x5b, 0xb8, 0x5b, 0x31, 0x2a, 0x89, 0x5d, 0x10, 0xa8, 0x98, 0xa3, 0x15, 0x62,
	0x4f, 0x25, 0x81, 0x6c, 0x4c, 0x95, 0x40, 0x29, 0x1e, 0x73, 0xa7, 0xb4, 0x2e, 0xd0, 0x5f, 0x42,
	0x37, 0x1b, 0x06, 0xc4, 0x28, 0x36, 0x7e, 0x3a, 0x4c, 0xcc, 0xdd, 0x0a, 0x8f, 0x08, 0xcf, 0xee,
	0x4e, 0x1e, 0x5d, 0xb8, 0x3b, 0xf5, 0xf4, 0x41, 0x95, 0x2b, 0x51, 0xc8, 0x6b, 0x3f, 0x57, 0x28,
	0x75, 0x6b, 0xae, 0x50, 0x68, 0x15, 0xa1, 0x90, 0x17, 0x7b, 0xae, 0x50, 0x6a, 0x9f, 0x5c, 0xa1,
	0xd0, 0x1b, 0xc3, 0xbf, 0x1a, 0xe8, 0x47, 0x27, 0xe4, 0xb3, 0x7c, 0x91, 0x62, 0x45, 0xaf, 0xbc,
	0x48, 0x4d, 0xff, 0x98, 0xd6, 0x8d, 0x7b, 0x04, 0xe5, 0x27, 0x20, 0xe5, 0x32, 0x25, 0xfb, 0x4a,
	0x5c, 0x75, 0x4b, 0x98, 0x0f, 0x6e, 0xda, 0x12, 0xfa, 0xcb, 0x49, 0xfc, 0x8f, 0x61, 0xf4, 0x2f,
	0x00, 0x00, 0xff, 0xff, 0xd3, 0xb5, 0xce, 0x31, 0x4a, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PersistClient is the client API for Persist service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PersistClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserReply, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*UserData, error)
	GetUserAuthenticate(ctx context.Context, in *GetUserAuthenticateRequest, opts ...grpc.CallOption) (*UserData, error)
	GetBook(ctx context.Context, in *GetBookRequest, opts ...grpc.CallOption) (*GetBookReply, error)
	ListBooks(ctx context.Context, in *ListBooksRequest, opts ...grpc.CallOption) (*ListBooksReply, error)
	CreateBook(ctx context.Context, in *CreateBookRequest, opts ...grpc.CallOption) (*CreateBookReply, error)
	UpdateBook(ctx context.Context, in *UpdateBookRequest, opts ...grpc.CallOption) (*UpdateBookReply, error)
	DeleteBook(ctx context.Context, in *DeleteBookRequest, opts ...grpc.CallOption) (*DeleteBookReply, error)
}

type persistClient struct {
	cc *grpc.ClientConn
}

func NewPersistClient(cc *grpc.ClientConn) PersistClient {
	return &persistClient{cc}
}

func (c *persistClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserReply, error) {
	out := new(CreateUserReply)
	err := c.cc.Invoke(ctx, "/protos.Persist/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persistClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*UserData, error) {
	out := new(UserData)
	err := c.cc.Invoke(ctx, "/protos.Persist/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persistClient) GetUserAuthenticate(ctx context.Context, in *GetUserAuthenticateRequest, opts ...grpc.CallOption) (*UserData, error) {
	out := new(UserData)
	err := c.cc.Invoke(ctx, "/protos.Persist/GetUserAuthenticate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persistClient) GetBook(ctx context.Context, in *GetBookRequest, opts ...grpc.CallOption) (*GetBookReply, error) {
	out := new(GetBookReply)
	err := c.cc.Invoke(ctx, "/protos.Persist/GetBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persistClient) ListBooks(ctx context.Context, in *ListBooksRequest, opts ...grpc.CallOption) (*ListBooksReply, error) {
	out := new(ListBooksReply)
	err := c.cc.Invoke(ctx, "/protos.Persist/ListBooks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persistClient) CreateBook(ctx context.Context, in *CreateBookRequest, opts ...grpc.CallOption) (*CreateBookReply, error) {
	out := new(CreateBookReply)
	err := c.cc.Invoke(ctx, "/protos.Persist/CreateBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persistClient) UpdateBook(ctx context.Context, in *UpdateBookRequest, opts ...grpc.CallOption) (*UpdateBookReply, error) {
	out := new(UpdateBookReply)
	err := c.cc.Invoke(ctx, "/protos.Persist/UpdateBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *persistClient) DeleteBook(ctx context.Context, in *DeleteBookRequest, opts ...grpc.CallOption) (*DeleteBookReply, error) {
	out := new(DeleteBookReply)
	err := c.cc.Invoke(ctx, "/protos.Persist/DeleteBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PersistServer is the server API for Persist service.
type PersistServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserReply, error)
	GetUser(context.Context, *GetUserRequest) (*UserData, error)
	GetUserAuthenticate(context.Context, *GetUserAuthenticateRequest) (*UserData, error)
	GetBook(context.Context, *GetBookRequest) (*GetBookReply, error)
	ListBooks(context.Context, *ListBooksRequest) (*ListBooksReply, error)
	CreateBook(context.Context, *CreateBookRequest) (*CreateBookReply, error)
	UpdateBook(context.Context, *UpdateBookRequest) (*UpdateBookReply, error)
	DeleteBook(context.Context, *DeleteBookRequest) (*DeleteBookReply, error)
}

// UnimplementedPersistServer can be embedded to have forward compatible implementations.
type UnimplementedPersistServer struct {
}

func (*UnimplementedPersistServer) CreateUser(ctx context.Context, req *CreateUserRequest) (*CreateUserReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedPersistServer) GetUser(ctx context.Context, req *GetUserRequest) (*UserData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedPersistServer) GetUserAuthenticate(ctx context.Context, req *GetUserAuthenticateRequest) (*UserData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserAuthenticate not implemented")
}
func (*UnimplementedPersistServer) GetBook(ctx context.Context, req *GetBookRequest) (*GetBookReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBook not implemented")
}
func (*UnimplementedPersistServer) ListBooks(ctx context.Context, req *ListBooksRequest) (*ListBooksReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBooks not implemented")
}
func (*UnimplementedPersistServer) CreateBook(ctx context.Context, req *CreateBookRequest) (*CreateBookReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBook not implemented")
}
func (*UnimplementedPersistServer) UpdateBook(ctx context.Context, req *UpdateBookRequest) (*UpdateBookReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBook not implemented")
}
func (*UnimplementedPersistServer) DeleteBook(ctx context.Context, req *DeleteBookRequest) (*DeleteBookReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBook not implemented")
}

func RegisterPersistServer(s *grpc.Server, srv PersistServer) {
	s.RegisterService(&_Persist_serviceDesc, srv)
}

func _Persist_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Persist/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Persist_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Persist/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Persist_GetUserAuthenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserAuthenticateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistServer).GetUserAuthenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Persist/GetUserAuthenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistServer).GetUserAuthenticate(ctx, req.(*GetUserAuthenticateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Persist_GetBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistServer).GetBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Persist/GetBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistServer).GetBook(ctx, req.(*GetBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Persist_ListBooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBooksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistServer).ListBooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Persist/ListBooks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistServer).ListBooks(ctx, req.(*ListBooksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Persist_CreateBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistServer).CreateBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Persist/CreateBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistServer).CreateBook(ctx, req.(*CreateBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Persist_UpdateBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistServer).UpdateBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Persist/UpdateBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistServer).UpdateBook(ctx, req.(*UpdateBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Persist_DeleteBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersistServer).DeleteBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Persist/DeleteBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersistServer).DeleteBook(ctx, req.(*DeleteBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Persist_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Persist",
	HandlerType: (*PersistServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _Persist_CreateUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _Persist_GetUser_Handler,
		},
		{
			MethodName: "GetUserAuthenticate",
			Handler:    _Persist_GetUserAuthenticate_Handler,
		},
		{
			MethodName: "GetBook",
			Handler:    _Persist_GetBook_Handler,
		},
		{
			MethodName: "ListBooks",
			Handler:    _Persist_ListBooks_Handler,
		},
		{
			MethodName: "CreateBook",
			Handler:    _Persist_CreateBook_Handler,
		},
		{
			MethodName: "UpdateBook",
			Handler:    _Persist_UpdateBook_Handler,
		},
		{
			MethodName: "DeleteBook",
			Handler:    _Persist_DeleteBook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "entities.proto",
}

// AIClient is the client API for AI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AIClient interface {
	GetSimpleGeneration(ctx context.Context, in *GetSimpleGenerationRequest, opts ...grpc.CallOption) (*GetSimpleGenerationReply, error)
	GetLargeGeneration(ctx context.Context, in *GetLargeGenerationRequest, opts ...grpc.CallOption) (*GetLargeGenerationReply, error)
}

type aIClient struct {
	cc *grpc.ClientConn
}

func NewAIClient(cc *grpc.ClientConn) AIClient {
	return &aIClient{cc}
}

func (c *aIClient) GetSimpleGeneration(ctx context.Context, in *GetSimpleGenerationRequest, opts ...grpc.CallOption) (*GetSimpleGenerationReply, error) {
	out := new(GetSimpleGenerationReply)
	err := c.cc.Invoke(ctx, "/protos.AI/GetSimpleGeneration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIClient) GetLargeGeneration(ctx context.Context, in *GetLargeGenerationRequest, opts ...grpc.CallOption) (*GetLargeGenerationReply, error) {
	out := new(GetLargeGenerationReply)
	err := c.cc.Invoke(ctx, "/protos.AI/GetLargeGeneration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIServer is the server API for AI service.
type AIServer interface {
	GetSimpleGeneration(context.Context, *GetSimpleGenerationRequest) (*GetSimpleGenerationReply, error)
	GetLargeGeneration(context.Context, *GetLargeGenerationRequest) (*GetLargeGenerationReply, error)
}

// UnimplementedAIServer can be embedded to have forward compatible implementations.
type UnimplementedAIServer struct {
}

func (*UnimplementedAIServer) GetSimpleGeneration(ctx context.Context, req *GetSimpleGenerationRequest) (*GetSimpleGenerationReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSimpleGeneration not implemented")
}
func (*UnimplementedAIServer) GetLargeGeneration(ctx context.Context, req *GetLargeGenerationRequest) (*GetLargeGenerationReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLargeGeneration not implemented")
}

func RegisterAIServer(s *grpc.Server, srv AIServer) {
	s.RegisterService(&_AI_serviceDesc, srv)
}

func _AI_GetSimpleGeneration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSimpleGenerationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServer).GetSimpleGeneration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.AI/GetSimpleGeneration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServer).GetSimpleGeneration(ctx, req.(*GetSimpleGenerationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AI_GetLargeGeneration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLargeGenerationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServer).GetLargeGeneration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.AI/GetLargeGeneration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServer).GetLargeGeneration(ctx, req.(*GetLargeGenerationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.AI",
	HandlerType: (*AIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSimpleGeneration",
			Handler:    _AI_GetSimpleGeneration_Handler,
		},
		{
			MethodName: "GetLargeGeneration",
			Handler:    _AI_GetLargeGeneration_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "entities.proto",
}
