# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import entities_pb2 as entities__pb2


class PersistStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateUser = channel.unary_unary(
        '/protos.Persist/CreateUser',
        request_serializer=entities__pb2.CreateUserRequest.SerializeToString,
        response_deserializer=entities__pb2.CreateUserReply.FromString,
        )
    self.GetUser = channel.unary_unary(
        '/protos.Persist/GetUser',
        request_serializer=entities__pb2.GetUserRequest.SerializeToString,
        response_deserializer=entities__pb2.UserData.FromString,
        )
    self.GetUserAuthenticate = channel.unary_unary(
        '/protos.Persist/GetUserAuthenticate',
        request_serializer=entities__pb2.GetUserAuthenticateRequest.SerializeToString,
        response_deserializer=entities__pb2.UserData.FromString,
        )
    self.GetBook = channel.unary_unary(
        '/protos.Persist/GetBook',
        request_serializer=entities__pb2.GetBookRequest.SerializeToString,
        response_deserializer=entities__pb2.GetBookReply.FromString,
        )
    self.ListBooks = channel.unary_unary(
        '/protos.Persist/ListBooks',
        request_serializer=entities__pb2.ListBooksRequest.SerializeToString,
        response_deserializer=entities__pb2.ListBooksReply.FromString,
        )
    self.CreateBook = channel.unary_unary(
        '/protos.Persist/CreateBook',
        request_serializer=entities__pb2.CreateBookRequest.SerializeToString,
        response_deserializer=entities__pb2.CreateBookReply.FromString,
        )
    self.UpdateBook = channel.unary_unary(
        '/protos.Persist/UpdateBook',
        request_serializer=entities__pb2.UpdateBookRequest.SerializeToString,
        response_deserializer=entities__pb2.UpdateBookReply.FromString,
        )
    self.DeleteBook = channel.unary_unary(
        '/protos.Persist/DeleteBook',
        request_serializer=entities__pb2.DeleteBookRequest.SerializeToString,
        response_deserializer=entities__pb2.DeleteBookReply.FromString,
        )


class PersistServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUserAuthenticate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBook(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListBooks(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateBook(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateBook(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteBook(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PersistServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateUser': grpc.unary_unary_rpc_method_handler(
          servicer.CreateUser,
          request_deserializer=entities__pb2.CreateUserRequest.FromString,
          response_serializer=entities__pb2.CreateUserReply.SerializeToString,
      ),
      'GetUser': grpc.unary_unary_rpc_method_handler(
          servicer.GetUser,
          request_deserializer=entities__pb2.GetUserRequest.FromString,
          response_serializer=entities__pb2.UserData.SerializeToString,
      ),
      'GetUserAuthenticate': grpc.unary_unary_rpc_method_handler(
          servicer.GetUserAuthenticate,
          request_deserializer=entities__pb2.GetUserAuthenticateRequest.FromString,
          response_serializer=entities__pb2.UserData.SerializeToString,
      ),
      'GetBook': grpc.unary_unary_rpc_method_handler(
          servicer.GetBook,
          request_deserializer=entities__pb2.GetBookRequest.FromString,
          response_serializer=entities__pb2.GetBookReply.SerializeToString,
      ),
      'ListBooks': grpc.unary_unary_rpc_method_handler(
          servicer.ListBooks,
          request_deserializer=entities__pb2.ListBooksRequest.FromString,
          response_serializer=entities__pb2.ListBooksReply.SerializeToString,
      ),
      'CreateBook': grpc.unary_unary_rpc_method_handler(
          servicer.CreateBook,
          request_deserializer=entities__pb2.CreateBookRequest.FromString,
          response_serializer=entities__pb2.CreateBookReply.SerializeToString,
      ),
      'UpdateBook': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateBook,
          request_deserializer=entities__pb2.UpdateBookRequest.FromString,
          response_serializer=entities__pb2.UpdateBookReply.SerializeToString,
      ),
      'DeleteBook': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteBook,
          request_deserializer=entities__pb2.DeleteBookRequest.FromString,
          response_serializer=entities__pb2.DeleteBookReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'protos.Persist', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class AIStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetSimpleGeneration = channel.unary_unary(
        '/protos.AI/GetSimpleGeneration',
        request_serializer=entities__pb2.GetSimpleGenerationRequest.SerializeToString,
        response_deserializer=entities__pb2.GetSimpleGenerationReply.FromString,
        )


class AIServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetSimpleGeneration(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AIServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetSimpleGeneration': grpc.unary_unary_rpc_method_handler(
          servicer.GetSimpleGeneration,
          request_deserializer=entities__pb2.GetSimpleGenerationRequest.FromString,
          response_serializer=entities__pb2.GetSimpleGenerationReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'protos.AI', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
